"""Type stubs for highspy."""

from collections.abc import Callable, Iterable
from enum import IntEnum
from typing import Any, Literal, overload

import numpy as np
from numpy.typing import NDArray

kHighsInf: float

class HighspyArray(np.ndarray[Any, np.dtype[np.object_]]):
    def __mul__(self, other: float | NDArray[Any] | tuple[float, ...]) -> HighspyArray: ...
    def __rmul__(self, other: float | NDArray[Any] | tuple[float, ...]) -> HighspyArray: ...
    def __add__(
        self, other: HighspyArray | highs_var | highs_linear_expression | float | tuple[float, ...]
    ) -> HighspyArray: ...
    def __sub__(
        self, other: HighspyArray | highs_var | highs_linear_expression | float | tuple[float, ...]
    ) -> HighspyArray: ...
    def __le__(
        self, other: HighspyArray | highs_var | highs_linear_expression | float | tuple[float, ...]
    ) -> HighspyArray: ...
    def __ge__(
        self, other: HighspyArray | highs_var | highs_linear_expression | float | tuple[float, ...]
    ) -> HighspyArray: ...
    def __eq__(self, other: object) -> HighspyArray: ...  # type: ignore[override]
    @overload
    def __getitem__(self, key: int) -> highs_var: ...
    @overload
    def __getitem__(self, key: slice | NDArray[Any]) -> HighspyArray: ...

class highs_var:
    @property
    def index(self) -> int: ...
    def __add__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __radd__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __sub__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __rsub__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __neg__(self) -> highs_linear_expression: ...
    def __mul__(self, other: float) -> highs_linear_expression: ...
    def __rmul__(self, other: float) -> highs_linear_expression: ...
    def __le__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __ge__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __eq__(self, other: object) -> highs_linear_expression: ...  # type: ignore[override]

class highs_cons:
    @property
    def index(self) -> int: ...

class highs_linear_expression:
    @property
    def idxs(self) -> list[int]: ...
    @idxs.setter
    def idxs(self, value: list[int]) -> None: ...
    @property
    def vals(self) -> list[float]: ...
    @vals.setter
    def vals(self, value: list[float]) -> None: ...
    @property
    def bounds(self) -> tuple[float, float] | None: ...
    @bounds.setter
    def bounds(self, value: tuple[float, float] | None) -> None: ...
    @property
    def constant(self) -> float | None: ...
    def __init__(self, value: float | highs_var = ...) -> None: ...
    def unique_elements(self) -> tuple[NDArray[np.int32], NDArray[np.float64]]: ...
    def __add__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __radd__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __sub__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __rsub__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __neg__(self) -> highs_linear_expression: ...
    def __mul__(self, other: float) -> highs_linear_expression: ...
    def __rmul__(self, other: float) -> highs_linear_expression: ...
    def __le__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __ge__(self, other: highs_var | highs_linear_expression | float) -> highs_linear_expression: ...
    def __eq__(self, other: object) -> highs_linear_expression: ...  # type: ignore[override]

class HighsStatus(IntEnum):
    kError = -1
    kOk = 0
    kWarning = 1

class ObjSense(IntEnum):
    kMinimize = 0
    kMaximize = 1

class HighsModelStatus(IntEnum):
    kNotset = 0
    kLoadError = 1
    kModelError = 2
    kPresolveError = 3
    kSolveError = 4
    kPostsolveError = 5
    kModelEmpty = 6
    kOptimal = 7
    kInfeasible = 8
    kUnboundedOrInfeasible = 9
    kUnbounded = 10
    kObjectiveBound = 11
    kObjectiveTarget = 12
    kTimeLimit = 13
    kIterationLimit = 14
    kUnknown = 15
    kSolutionLimit = 16

class HighsCallback:
    def __iadd__(self, callback: Callable[[int, str], None]) -> HighsCallback: ...

class HighsSolution:
    @property
    def col_value(self) -> list[float]: ...
    @property
    def col_dual(self) -> list[float]: ...
    @property
    def row_value(self) -> list[float]: ...
    @property
    def row_dual(self) -> list[float]: ...
    @property
    def value_valid(self) -> bool: ...
    @property
    def dual_valid(self) -> bool: ...

class Highs:
    cbLogging: HighsCallback

    @property
    def numVariables(self) -> int: ...
    @property
    def numConstrs(self) -> int: ...
    def __init__(self) -> None: ...
    @overload
    def setOptionValue(self, option: Literal["solver"], value: str) -> None: ...
    @overload
    def setOptionValue(self, option: Literal["presolve", "parallel"], value: str) -> None: ...
    @overload
    def setOptionValue(self, option: Literal["simplex_strategy", "simplex_scale_strategy"], value: int) -> None: ...
    @overload
    def setOptionValue(self, option: Literal["output_flag", "log_to_console"], value: bool) -> None: ...
    @overload
    def setOptionValue(self, option: str, value: bool | int | float | str) -> None: ...
    @overload
    def getOptionValue(self, option: Literal["output_flag", "log_to_console"]) -> tuple[HighsStatus, bool]: ...
    @overload
    def getOptionValue(
        self, option: Literal["simplex_strategy", "simplex_scale_strategy"]
    ) -> tuple[HighsStatus, int]: ...
    @overload
    def getOptionValue(self, option: str) -> tuple[HighsStatus, bool | int | float | str]: ...
    def addVariable(
        self,
        lb: float = ...,
        ub: float = ...,
        obj: float = ...,
        type: int = ...,
        name: str = ...,
    ) -> highs_var: ...
    @overload
    def addVariables(
        self,
        nvars: int,
        lb: float | list[float] = ...,
        ub: float | list[float] = ...,
        obj: float | list[float] = ...,
        type: int = ...,
        name_prefix: str = ...,
        *,
        out_array: Literal[True],
    ) -> HighspyArray: ...
    @overload
    def addVariables(
        self,
        nvars: int,
        lb: float | list[float] = ...,
        ub: float | list[float] = ...,
        obj: float | list[float] = ...,
        type: int = ...,
        name_prefix: str = ...,
        out_array: Literal[False] = ...,
    ) -> dict[Any, highs_var]: ...
    def addConstr(
        self,
        constraint: highs_linear_expression,
        name: str = ...,
    ) -> highs_cons: ...
    def addConstrs(
        self,
        constraints: Iterable[highs_linear_expression] | HighspyArray,
    ) -> list[highs_cons]: ...
    def minimize(
        self,
        expr: highs_var | highs_linear_expression,
    ) -> None: ...
    def run(self) -> None: ...
    def getModelStatus(self) -> HighsModelStatus: ...
    def modelStatusToString(self, status: HighsModelStatus) -> str: ...
    def getNumRow(self) -> int: ...
    def getObjectiveValue(self) -> float: ...
    def getSolution(self) -> HighsSolution: ...
    def allVariableValues(self) -> list[float]: ...
    def val(self, var: highs_var | highs_linear_expression) -> float: ...
    def vals(
        self,
        idxs: Iterable[highs_var | highs_linear_expression] | HighspyArray | NDArray[Any],
    ) -> NDArray[np.float64]: ...
    def constrDual(self, cons: highs_cons) -> float: ...
    def constrDuals(
        self,
        cons: Iterable[highs_cons] | NDArray[Any],
    ) -> NDArray[np.float64]: ...
    def changeRowBounds(self, row: int, lower: float, upper: float) -> None: ...
    def changeObjectiveSense(self, sense: ObjSense) -> None: ...
    def changeObjectiveOffset(self, offset: float) -> None: ...
    def changeColCost(self, col: int, cost: float) -> None: ...
    def changeColsCost(
        self,
        num_cols: int,
        cols: NDArray[np.int32],
        costs: NDArray[np.float64],
    ) -> None: ...
    def changeColBounds(self, col: int, lower: float, upper: float) -> None: ...
    def changeCoeff(self, row: int, col: int, value: float) -> None: ...
    def getInfoValue(self, info: str) -> tuple[HighsStatus, int | float]: ...
    def deleteRows(self, num_rows: int, row_indices: list[int]) -> HighsStatus: ...
    def getExpr(self, cons: highs_cons) -> highs_linear_expression: ...
    def clearLinearObjectives(self) -> None: ...
    def clearSolver(self) -> HighsStatus: ...
    @staticmethod
    def qsum(
        items: Iterable[highs_var | highs_linear_expression | float | HighspyArray] | NDArray[np.object_],
    ) -> highs_linear_expression: ...
